---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1028skkftk748v9ju8vvfydupt3mly5qlrlteduymnz5epl752cwqtdf2zj"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1028skkftk748v9ju8vvfydupt3mly5qlrlteduymnz5epl752cwqtdf2zj"
