apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:KKDRMAojTYu+RFT3pwP0Zhrq/jxbaE9LAQxpf27T8o31XsPr,iv:grcvoY+fECYZMvWW7iBuBSZ7WNhBPwqfRaUlxIb3HTA=,tag:OQRurrG8cY4aG/s1nQBVHQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:4HZNMlm2xIoo6uPt1K16e14w9iVI5IHm02348QB6aDYG9iceZPkjC+jyhzBRE9W69OwJFhcb6sTK2JiLe8iILYyfbrbsjElCzpXD+J4eJGWVLGbJjKZlTnHkTBrsx8nsV39McqSruU+PGddQswP00dP1KfZIKLt0HYLOIe2N8Jpdj2c1VpZ8LV0WPM8wz+dyaAtIfhBerWP1U8ktTk/exK5NuoDag/Knl2l1062uIQ==,iv:md/8K2uPNkGsNm0DcSw+Z8AhIBxuWJEnmkk+XK+CtVY=,tag:W0ha9fPh/izBQxB6orB3vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1028skkftk748v9ju8vvfydupt3mly5qlrlteduymnz5epl752cwqtdf2zj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YU1NSW1Jd2F4bDRYRE5r
            U0NFdVRCQ0NqNkt1TWU0dU9GV2dXTGJyN1FNCmlIRDhQM2FIUndTY2xWL0o4ODZm
            STNWcm1tQzdnTWg3UjFieGRIQ1ZwTUkKLS0tIEZKU093N3FVYWIrSzlqS0JwTy9l
            SGNGMEtGT1I2L256NVk0cDBJMW5tMDQKQC4sCC2RjAVg98Mo/pH1WsAqh71x+nWB
            sOrTGRMPI4EJ3KuQc8TMnL1yat0Q5O4Hq01Yh/vMu3aQ3MiefMwd2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-29T02:37:39Z"
    mac: ENC[AES256_GCM,data:N1SpE/7RquWP2AXfxvn+jOt1VoVhoNwO9m8gFkETIFvYcJ3PYSoRslXVKmRRwqnd7spOYwNtnqtZ4nLc1gu/LUiRlX2fGHfGkjTa+YrXHPTx6eX9L3A5P6EpCWKRumQTdUGQ9SHAT9S7Wl37jgSbRNgS1R5GByOkZxV7ePkVvy0=,iv:bd7sYXyhqJkeyzvSHyGFyPY+vptBxCcFf4cFsMjq8XY=,tag:yL6vRshqKzRyEx44zjopTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
