# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:U8YwUYeKqA==,iv:txHgFX2E/v7VcqGt14zkdqRUYZOu8pikEFHGxLXuTmI=,tag:+OXGU5o2o0/60uUxP5mq7g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Za5hcCb2tEqHjet8NK4U9Qzx5dApq45VGQ==,iv:YARja0eqsuXGK6+abZ5gG7KwOROUArd1FZsyLXsHzS0=,tag:jJu6A1YC6SBAAiqYzA635g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-02T23:46:45Z"
    mac: ENC[AES256_GCM,data:/jOd/MH1CAdf6h0jGx3oXOfwbc0v+DDRmIfX0vn6HaC/UQHgRtwJIpCtS9PkldEAoDHfeWU62sWHhIIG2aDmUkaKCiKSDGDnGeZa8TWNVwCa0OCS3ah/lOcxpBSFOeLHpPtqoUMEN0sCpdu7yNq0KEBHb/9gKxSKF35fWhy5eOg=,iv:v+ITMEwSgsi8ntfWeN6snL/sKHbavs8bZWpXL/hualg=,tag:cbAiElb8gFBSj3MUnaLvyg==,type:str]
    pgp:
        - created_at: "2022-01-02T23:46:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2ch0fbYWS5cAQ/+OthHGStRwpMAIRdZ/5R0etKQiow11JOApvhsABf7xkF2
            uiK61AZhS2ckKsFRiDinzyuDitM76TFcRqG3GD1r44qwbt1u7aHZQB5ZiXSJ2QV/
            hlFYGQ5gH1MHKRIAYNYETXQJXR3fGylVa+zhRtP0rin6h1gS/pk2ImzRnnjxUXmY
            Mt7l8GDHx7/IHAheurU9wsub4GUBbP8oUMs/QYGhmlPd3ZweGh3yXY6l0K2l6069
            kSs/cTDKRxxDJEfJ62BH1iktVOPXx/ty+skyoHjNd2vu6MeSLMLiCiGcrhpvn23G
            A/O/JiL8k9XUJjtonSM2eLP1PZiTwzKEZCsNzex0/VT6QLM+77RGBfLAiY0Yj/+E
            LDQqHOeAuolt4OavF7fKSaFKptEAzuUOqju1cJ8ZR+5PfAps3LabWUgGd3/+4vcO
            6emlg0zegjGNvEU9f+BHXVJOp9+FjA4OnVrFvt1Nujo9RAPTWFNtcXhrjm8ps23v
            KB/xoHCB1ysxzl0AkCYSK9+sDLniMnOxRudJ+Mo9V5pA9ouob5giK3Fp1f8YoDUH
            LYWbNal8KJAuwvSOE9Ti0lFYuEf9LLTu1i+KlanW92KBLaO+RjDyjASgND5xXCu1
            5LxxYZErhCRbjqTPotFNUO1HlhjQxEfeYwloLae/Twa+esJAzGi3A5rmRmDDP0vU
            ZgEJAhCiMVMjkGc55F85A5pwcHeUHEKl4gYESvZ63AmO/FERXN60NOml4BnmFAVd
            BDIhC2EHXhA2mNkS3cB8vTTl5nnsaFv6thD5DNOkcv51ihzpYY6HZmkdvFHrST2w
            CcP2zBLM2g==
            =NvLW
            -----END PGP MESSAGE-----
          fp: DE6EF324C5EB454CBA21289BFE30D92DBBD39C6B
        - created_at: "2022-01-02T23:46:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/Yc6nP8mM4lARAAhw5vrwlp5ZdmNaYEHDyYQwPeWo1BCMOQHVEIkObKB2HW
            A2J9dwsMd6jn2RQibf8LtnjcfkgfY6bZq+plWBgLogh1sMj4fcJ6wKl8kvPtZSYw
            s98RTZYmD334B83F/GiRZua1K2F+gx6KoHZWF+KBdThkNwBR282223RAIhI+MaDY
            VN5rCHzXIQ2mGvGIX0CPl+PPbtwu78BMInDbG2IZr1wUQO6gKJcA8bpz/KWL+Krl
            fitaGV+2LYDvfPZEfE8NUlK/OL02oR/rF0Wy5Wz5YQZb7N5zn2RnyxcSUzZGBU2W
            QSuaRAjOc39mAVI2Ha4tTOM8rSPWGMa83EDt4WoF9IVnERygbL8dJsLC+GGW2XJ6
            f0QF5rDlrDhyseVT6u8NK9bDDJtlWD9L8tmXxJTEhLjnLs1rZo8ZjMvx7hlXh9ff
            s6ijxHxBlDW0rscqK9UIMmb3oLV5PkRZ0ggW8mLxA5nkIm5L/eos9DgYf1WlSGFC
            t4KHpdRWYdI+XZbsswsJiugYHeWRYihq8N5HKnvawzNZCdnbgISdQfO6CA5Xfvlq
            2QqiupIhq6X/S5XDNRhtzUjydIiBjonuZWqpl9ITVnVVhCU0+7Ow8IuTgQN336Uf
            B4H/ShtpOUPUVblW9k8dkvk8q6o2vxyfzPIA7cuaLC0LaCCWWsq2YZlWl2w019LU
            ZgEJAhBHSf2cQnQbiGhu25nMJqzzGFuJVcmzvHi2ldRksU4ROSbt3QcqpmiYHyJB
            AV9xD515ady6K1xVpPEcpfm3c5VZjbPWS2GMN2hXDEVV40vDrqOepDPW4ZGEtfWi
            Ecc1lGE3eQ==
            =xOSo
            -----END PGP MESSAGE-----
          fp: A5FFF81486784E737E0CEA3A78BC6530D815488C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
