# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+hoeapz+fm/v7UVcdn0hFQ==,iv:4Ud+h5XDmrvaokIpw8qBjui87+OfjsyBPDq1XKV6O1c=,tag:VIw0/bnmBBeZFkdc7ALuvA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:jQC/C2v3CTCgDqt+JO8UjmdRWnggEOvQXw==,iv:n7wMsOhcBzALySmEis/cl2u+gSA12TauzphTuzTsKW8=,tag:XRTtfZa6IVAkodNJ0jaftQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T17:44:17Z"
    mac: ENC[AES256_GCM,data:II4Wpe9GWtWIutTPiP6wu3zH4KOADJkoVW+4ntJBpsamns+Q3bu6vlOIXu9QdntbBsa7ABZPx+UJMBvrG+HSE4FDPWEXoo7uzoViib3wiawcI3sGZdcQ62tmNPPLnkipUdeAlDC0abBVeP1TBIJ8GrNiXVFVV/fZJop/mVPrU2Y=,iv:PfTCXSEs32FcBoiM7f7O33pRKqqoVK3dMo/df5aHcl8=,tag:0rAOsSejv4S3vYoE6IGjgg==,type:str]
    pgp:
        - created_at: "2021-06-10T17:44:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6QW0qA3M1HvAQ//T8kCW20q68dHzXD7tZil5culZNRUsJmfynJZB7LkLG96
            ITQfs8YzI8AJqeFh/xu0t1URER53H6qRi8+SrZUeYHU5hWmiV3E78BFE6d4sTqz1
            lN+qNO/LnNgMM4n65XpF2aD2hMDL7V9x/nUzwNrLTSSDwNdjSlXAYyxpYOBCjhKO
            AIsxj1zTYDE+LOj3A7Ax1ZTEaNHcPEJ0bj9zhcJszG+mJaRZ/9FJfGabS8Q5heW3
            JDH0FYNwlyzN0zS2lPjQi+B7Z15lhtuJvNPxrgLOqsrgSF7gOZ7Fw9WJ+849VTcJ
            IZMM33nATz9/WfvGmxyo6kgAs4BPRwE9YdZIWNDkQrqn9RNNfppisIoh2lImdENb
            NCpoLWEH/8oCYqWHvJXDX65vVMQ5AvF+8Fz7wVNSkv6dNz6wclb80MAUWH/Fhwn6
            YCb44eIaQRJywZjrsCr3q7amysxVSGnDI/6x72S45HCOSGLn8+iUd+trvaEvRplP
            wMF8pey7LBZ5CfVXjoSxf9tY3b4sFH+RTqqEIGldkGhxs5i43EEckm5uFai294SO
            kNIetQE2ekCSPv1DtpKpwXRHSEz45GwLhZC4OCt6W5qsLtBGz5+fOQM+PaDrh1K5
            sXRAG8xFNWrL6qT0wP/JtThm6yUpq9JZAoXZw/SYWDBmNtKI64Y4CnUrPKATfz3U
            aAEJAhVnokD6l5XFDVeTOCkctvp0f1c9u5qoMi5FwoaZ5A7augBUqARd14Wa56Xj
            QauEpsm4M3WEVg6a3W5tgKAqjtCbWfd4My/kUgc7kI176aHSbe4YIf0Bd82xkpGo
            QeXCyvHtSV3u
            =yS6F
            -----END PGP MESSAGE-----
          fp: 71D132017F08B92A645D1160C68CA70EADA2C203
        - created_at: "2021-06-10T17:44:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/Yc6nP8mM4lAQ//RiA6lBHvlozhzYlpHZmLRXYKF3TJBkh7DtcPQvbEyDuB
            bbkHiDm80/TNxyD/9UC/zSGGgcIfBDAiKlV6kh7b8jNEA6PlLCC2jvTdFexYBV1g
            FadOzqMCdQA9UkHzeARRvNY0eAHLQj397QMgoVrBDPNf4Lf1J8Z5SSamoBZ3Le84
            XXQtThS2Sj9J+/IZSNY5h6wXou5cDE10S3EjyEy99OeVB/0Kg5EbM3tA/ASD9LYJ
            ClPsfe/+ogRb/WNCt0n1g+++yHJzHWp34rFKQyAYzxt6BaT91O5jk9gwnAGDKyv8
            59bEr9Aq5K1O/VOA89qPPw+EfZfFADqFwu0ICgNlIpZeqA5V8wdSWNvoQ0JvvO+D
            fqXvtZP2rnUvzF859shKrWHz9wjlaFIjm7tkb+vSeqzurtNPKOIXPL8TS2LPA/Rj
            D54z92zXeohyaxtvjxJeSfBsZk6sly7r7rEDwpaSms8I3RvadhJ9HlxBi+ms7HBM
            HpWY2YPEVFrreBtlQQiH9VwSyl0xq68bR/mHxvx0KFUDOEf6OqVQ5STucmQWSbDI
            hZykcQPA1j/P43cjY0X9bV+IGYs08xGOBtytsGsAt6g4CMnCDdMB2o6ujCmzeBtb
            ktnY74548YVsGHr2HxF8HXcHDU+bdroMiGzrpDqmSQ4yfmwTfEgOKRO2bUl2KIXU
            aAEJAhVrHwjwOGY0/3QeRsOX2skCnjnHM75tYt/itFc2vXuLqFe2pqcrYRgRvdMP
            eDi3yE9cUnv09G7dfLWNLNdH7SGFkrzJwYP/KFWMaj1DVfpDD2gqCvP8qpoqnw4f
            qL9eLnZ4fuKz
            =KFWw
            -----END PGP MESSAGE-----
          fp: A5FFF81486784E737E0CEA3A78BC6530D815488C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
