---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgresql-pvc
  namespace: collab
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
