# kubernetes/apps/monitoring/kube-prometheus-stack/app/helmrelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: kube-prometheus-stack
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      adminPassword: "admin"
