# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:aDG4HzvClkdLn6cpGRg95Z/D5l7iaoVyDnL1CkZ/ETsawYqVBdVF2A==,iv:FGP+y/+VQGzoGQ+w4E1wvQ/QmIrH74yVQHi48Qn/1h4=,tag:BOS6ty+YhqpG6Mc/2Kym9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-10T17:44:18Z"
    mac: ENC[AES256_GCM,data:s1fVTNZrmGXJpwnx9lqI8PjqNBUfVa4flRgwopiCE88iZZdWM2kt6t8AU5Aa4auLSFvAy84mmjHeYyyGN0Nk6uZBPEc6RCOT/Q8AP+zUUVWRac8jvoFI8qc/4QhoGzySCNEOKGzLa79OuiWRXa9t7nfk2LrBW22veA+UzABLfEg=,iv:iM7ckhZwh5IxZNxYQIEjxRy4p1jqlFVhUTkpqqaV5wg=,tag:oHoeEc7EGj9J3IvElrythw==,type:str]
    pgp:
        - created_at: "2021-06-10T17:44:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6QW0qA3M1HvAQ//cI17qKoQ6p4qKvElGk3ThX4YjDAFXHiztuwwihEF3sqa
            cehhW9mY6uyhoOU4hjhkQvfg3lrALRg7AEOpWOxQiI6aLXmIDNxWX5iklakaBsWL
            wdsh5kBYu6yyHdtiOCpQwgku4YSPo/Bxqj8BoqXXH9zAlweNZR4vXnTTj4hZlnBy
            w/yyQcMQyVWtYS6ypkbe1iMUKCkQu+aY9JDybri6l1SZHQ9Z1iSl+2qbMm1o3i2E
            PqEvGboA5iiBciFtAoCT3S0V0TOxLNUNWaZc910/VS7LEpvfwaMxhC4/V4Qe6wVA
            ifIkgN8znLlqjh5+JtrtVU1MGBdpHDC8fu2DH78xYroEmP1ILByLuJyqGT79mDUw
            u0irennP0DDW/MDqUvlV2yYLqpPKLEeCwdIe3T40Xc+8Bggsc1LMQpdiPrVcI4xF
            k1NmFhwSoMU09yarDIHUCasDZgxuF3lUhrGk/xogDID6CqJpma3uTl4UzaXk0hjq
            HxAHgk+gMAkttZsZv1fq66X3zJfjCOzHg5QvPji1MUGWV1I2dps+4/90OFymazC6
            X9mkhH/96Ji20626RC+lTYEv2nf47qZkvktMf9JHZLaZrfhbdZzeLiWdf4X8yVPI
            Fk2XuNhnh1uqkP1FsO4ETCS+rlxdNXdg92/7j2cED0VnI+iAfCkFbeaJCkOWprPU
            aAEJAhW3AttDhkI0OSP/xVbIsHmhGOThKQx3tkbMX3tH+qE5QlbZIFxp5sGdvTXE
            Ij6NC6/0Z1O7itIzg0MfQp6gJNpf2ZjqQDHq+oNnjPEtPAZ9IvimuSVxv9uect13
            HixhicCuGLQL
            =PD8r
            -----END PGP MESSAGE-----
          fp: 71D132017F08B92A645D1160C68CA70EADA2C203
        - created_at: "2021-06-10T17:44:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/Yc6nP8mM4lAQ//WI8cQ4q+4FMNlMpnS3gWLMzIm6oyBnJJbWMM6w0apAty
            UAt/pLm5Ezq1wk7eQ7L0H13wCjJI935Did6Swu5UtMUIkqHXWypVK6YfLsONo+8Q
            CIlY9B2vBOwir1lLNU43FR5R4bTnTBxHl7F/rebqXHJjKQW5h4p0CCqq5Z8ggvqX
            /MYcHt+NQjd2SZEc3S+Qhdz8hqYWCRg4Rji6P/S4ulyFpjONKTy2Tdm9Q20+EE50
            dK4bN/PcA5omeBuxpzjLaHIxvrdwXDWfBK9TeW1q3bl6B6VmUfuqd526nT+UahVW
            Gt1VBufdav/DItw+aQAS5I3mT8jVXU1Bdjcyo+P1JelDMMto63BY8NvJdOg1pcIN
            DGS/VdVpzOqPpFgtyx/jYDz1gWr+bjd/f0IvhRxx8sUbgfsTfp/VJwuBEMjTN5rs
            X1T0BG6pvjcLCNaT/K1DaN7yNJmH/yqCCiUxr4lbHkiSorOogSG2z7yV2OahTT0g
            y/Hkcfle6pYHxp0lHa0gEhfPUH9cRsSAH7DTT/5BVvLzoVYq7e+yrCvTr8x9jqr/
            JA9y+GZiiaaM+R6MbB/TfG2pSRPT9Vx73btuYa4G3QbKTAJjrk8awecguRUonM/4
            IMrnL9IBpGBvTYwaUdIViBKQ6mhxVcuPeZhVkxlY/HAfCdGqaBOom2uXi6I/GEPU
            aAEJAhW7ZtGV2IBYwSp5cjMpBhXzpkfXadwLgWq0VEvDRIvMw4DNZdirisV1GCb4
            C6mFGJrTbl4yzAUVSm0L2k9wfT7rqe241nocCOTVzDr5FiOGO9ewrPQlklANd+aZ
            fzdht00GV5sv
            =sarS
            -----END PGP MESSAGE-----
          fp: A5FFF81486784E737E0CEA3A78BC6530D815488C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
