# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:/2w2aF7xQPRrp4ligjipx/kmceKqQsEUZCjPePiAavBIYNsXn8cKXA==,iv:axUsdnmEahMiiL4s648Yse4i++YCuIWh1GTedQlukE8=,tag:GQU13W2HvD7nJYfPEoGHBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-02T23:46:45Z"
    mac: ENC[AES256_GCM,data:ur0qT8EIyuETyrXyRnaOFVAG9YI8Z4UMGAJfEJ5ItIOl3pCdPSA2b78XJpmIRrxoVsFz9Jgza0+A8ksv9rgyiPqY1RMDsQPlXlpA+1ZqciCbdc0pbEbmMjTH9nOiq6ettpfhp2BPAa3Q3IiWkp2H6PPcI9KSGaacDcBx/e6LUu4=,iv:tk8Mi4PNoTMONRgQwK6+ZnsuFUZKbzwcPqt78+NbZT8=,tag:/crbZcFH0UVA3ptjA17lJQ==,type:str]
    pgp:
        - created_at: "2022-01-02T23:46:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2ch0fbYWS5cARAAsoPuncxrJYJWy473TQXqFeKGgB2/PvbyqEpqnurWyNWa
            SyS0RkihorACQABV6K6A+AxgcsfLs9r4MhtKOLAOgsaceGVRI7BveDYccifC5xyF
            gx/ihInJfP3H8yUVqVotH8xuspS6XWmwgYhkLnDukw11ETB54BJrhFrp3siUcjQR
            1QrdtopvQDrRBT46FyaxXqgGJ956RW+VYO10qLW7CCbbWkqKJqjf7o21xk2tFXx9
            fBLGI7mlY90YVPvA5DuTNuu7Wa6lpJFdHVw7htLJcSuBhV81JpCYmXY0uwxaa3N0
            KoUVjiFaTISXDjR1edjc1yhC43sc9QyiYyghEDnhew0iPUkK/h9bU+cP347xqqHg
            88N+eGgEZ6pp1QnkQ73xCvkS/T4Fu9NfZ0MyrjJMdbdKGVrIREPgJ3Okana4YwCt
            jbc25u9mAEi5o3U4HZo5/3naqDL29kPKt9CkY2cuZ/MCUErFC+cGmfyFIXg+KRun
            C5KDSstSuqfMkl/FRJ9uq+n6LazgB3oAuMtmhVqV71LwiRxfCKs/Cw75Ge9l+8YH
            k2/WNpGGnMTqCAYgUZD8iLmTXmfsJmWzgijTPRz+jzxZRvLItP4/SivxxLKKY6Bi
            YaIQCbSwjM7o2qslHxAcU8rOQAuTFVU03sY1c6akZw3Yq7JtIKZ9859BEUqJbZnU
            aAEJAhBgxfLjQJnf+/bajxOiQVAXt4jvML7BfbgOUd50dn4NrTxnTxx6BRCfyf8H
            PozmRVhNXy3cVTo9mO5V2e7+/NoGw+hnxPJaJn+A3CgxEJ93QePlR9xwsx22cOFw
            V3r2vCiBaT7/
            =Wg7N
            -----END PGP MESSAGE-----
          fp: DE6EF324C5EB454CBA21289BFE30D92DBBD39C6B
        - created_at: "2022-01-02T23:46:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/Yc6nP8mM4lAQ/+Phu9qfCotAa5kpeO29bPkSOmrEi0gz0eP9Dqg5eiqSP5
            +7o467YC00lab+iWXf0v9oeQMu4DEX+XMobujztWUO5Z1wM5TS7Hpd4xkMnObnBr
            2w32ivhgAhYcDyGP/pfs911ZaJw4FD8yi7rhD51AZVyfxb61I9XyUzE6Ce1YNhwd
            p7PLFcUGiIGSxFtDSqXHriamw/SiKhrHbk4ZE2e3UOE6Fk50oFOy5TNqGVkEvMVt
            sSKau/0axFKTLZM+6GA/TENvDp67xzHyaZ3V8vVKvMGU+KtCXNdETomtI/diTWSl
            oAp4eb/vFyjg9ckVaezi5wsQCuHlo/ijwDM5JMm+cmF6MqA22eblVwhR7a/y3bjx
            E+XYnQI6pHXqlFwRQ/5QvR6v/MvJehN/A8HZsaufs2Gq+0+mTC2WYbf558gXL3Nv
            3saQLrZzokWh8wnKG5bFsIO81TrYv9+42HJGb3YVXhDxtnhuqF59moixVH82wUpz
            HekJURGg0vInZzp1kphVB0Z50V0+2lceadSo0sNkhvCAGw3czKHP3rBLgU3A9cpS
            Lby5kK55VcH7sUzy6wY7C87KAxO6tD4VNFZFrcMCTOwsdH6uBthwAZ6Jr71t54i7
            Dg51h2RVPieHcvngQDr7n4AtEi9VOkn1un4G+MorlsmnR6hEv66YsWb/iBI/j/nU
            aAEJAhBNm4SARVuKSEcreTpCpWItGRQN4NAW9OnBWUEQD0R7IpNJZttUVjJanyzO
            1jhKoAGVD78XnkdwR44+rvE3HX7PVxnqSK0Ook/zLS70JQEiRq8geRhbEs3ozFoY
            hzoYZEB6WOwc
            =cmsE
            -----END PGP MESSAGE-----
          fp: A5FFF81486784E737E0CEA3A78BC6530D815488C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
